export enum AuthErrors {
  WRONG_CREDENTIALS = 'WRONG_CREDENTIALS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_PASSWORD_INCORRECT = 'USER_PASSWORD_INCORRECT',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
}
